# Generated by Django 5.2.8 on 2025-11-24 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_produto_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentacaoestoque',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='id_produto',
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='produto',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='app.produto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='data_movimentacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
